# table
# Load the parameters, then define table surface in ros node
# The table is also considered as a box obstacle
table:
  position: [0.00, 0.70, 0.35]
  size: [1.00, 1.00, 0.35]

# camera
camera:
  position: [1.00, 0.00, 1.00]
  orientation: [1.00, 0.00, 0.00, 0.00] # quaternion, rpy, or whatever convenient

# We can define any types we need
# static_obstacles:
#   - {type: "mesh", file: "package://benchmark/meshes/something.dae", position: [0.7, 0.0, 0.0]}
#   - {type: "sphere", position: [0.00,  0.70, 0.35], radius: 0.35}
