# table
# Load the parameters, then define table surface in ros node
# The table is also considered as a box obstacle
table:
  position: [0.00, 0.70, 0.35]
  size: [1.00, 0.5, 0.7]
  color: [139, 69, 200]
  
laptop:
  position: [0, 0.6, 0.75] #0.35+0.7/2+0.1/2
  size: [0.3, 0.3, 0.1]
  color: [0, 0, 200]  
  

# camera
camera:
  position: [1.00, 0.00, 1.00]
  orientation: [1.00, 0.00, 0.00, 0.00] # quaternion, rpy, or whatever convenient



# We can define any types we need
# static_obstacles:
#   - {type: "mesh", file: "package://benchmark/meshes/something.dae", position: [0.7, 0.0, 0.0]}
#   - {type: "sphere", position: [0.00,  0.70, 0.35], radius: 0.35}
